server.port: 8761

eureka:
    client:
#        for not working in cluster
        register-with-eureka: false
        fetch-registry: false

logging:
    level.com.netflix.eureka: OFF
    level.com.netflix.discovery: OFF

#Should be env property!!! This is just for simple example
spring:
    security:
        user:
            name: netflix
            password: eureka